FROM ubuntu

# update the container
RUN apt update
RUN apt dist-upgrade -y

# install some essentials
RUN apt install -y curl git wget vim

# install languages
RUN apt install -y nodejs npm python3.7

# install dotnet core
RUN wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb
RUN apt install -y apt-transport-https
RUN apt update
RUN apt install -y dotnet-sdk-2.2

# install azure cli
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

# intall node version manager
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash