FROM nertim/ubuntu-dev:20200301

# https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local
RUN curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
RUN mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg

RUN sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-$(lsb_release -cs)-prod $(lsb_release -cs) main" > /etc/apt/sources.list.d/dotnetdev.list'
RUN apt update

RUN apt install -y azure-functions-core-tools

RUN mkdir sample-function-app && cd sample-function-app

